@base_url = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}} // Pegando o token de autenticação

# @name create_accounts
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "die4412123154go@teste.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{base_url}}/sessions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "diego@teste.com.br",
  "password": "123456"
}

###

# @name create_questions
POST {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "1Q123123ual 1232131a sua cor favorita?",
  "content": "1G12312ostaria de saber qual a cor favorita de vocês"
}

###

# @name fetch_recent_questions
GET {{base_url}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
