@base_url = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}} // Pegando o token de autenticação

# @name create_accounts
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "diego@teste.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{base_url}}/sessions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "diego@teste.com.br",
  "password": "123456"
}

###

# @name create_questions
POST {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
